# azure-pipelines.yml
trigger:
- master
- release

pool: 'pool-linux-b'

resources:
  repositories:
    - repository: templates
      type: git
      name: cloud_devops_evaluacion
      ref: 'master'

stages:
- template: templates/deployTemplate.yml@templates
